"""create station model

Revision ID: e951cac66f25
Revises: d5ae416e3cc5
Create Date: 2022-12-31 00:32:11.346764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e951cac66f25'
down_revision = 'd5ae416e3cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('total_collection', sa.Integer(), nullable=True),
    sa.Column('total_discount', sa.Integer(), nullable=True),
    sa.Column('passenger_adult', sa.Integer(), nullable=True),
    sa.Column('passenger_kid', sa.Integer(), nullable=True),
    sa.Column('passenger_senior_citizen', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station')
    # ### end Alembic commands ###
